runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /static
    static_dir: public/static
    secure: always

  - url: /(.*\.(json|ico|js|html|png))$
    static_files: public/\1
    upload: public/.*\.(json|ico|js|html|png)$
    secure: always

  - url: /.*
    static_files: public/index.html
    upload: public/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
  BACKEND_URL: "https://pokemon-backend-dot-${PROJECT_ID}.run.app" 