runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.6

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|html|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|html|png)$
    secure: always

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  NODE_ENV: "production"
  BACKEND_URL: "https://pro-pokemon-backend-dot-${PROJECT_ID}.run.app" 